name:  LogGenius Continuous Integration

on:
  push:
    branches:
      - master
      - 'maintenence/*'
  pull_request:
    branches:
      - master

jobs:

  build-and-release:

    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore

    - name: Publish the project
      run: dotnet publish -c Release -o publish_output --nologo

    - name: Create ZIP archive
      run: |
        $publishDir = "publish_output"
        $zipName = "LogGenius-${{ github.ref_name }}.zip"
        Compress-Archive -Path "$publishDir\*" -DestinationPath $zipName -Force
      shell: pwsh

    - name: Set current time for asset name
      id: get_time
      run: |
        $current_time = (Get-Date).ToUniversalTime().AddHours(8).ToString('yyyy-MM-dd HH:mm:ss') + ' GMT+8'
        $current_short_time = (Get-Date).ToUniversalTime().AddHours(8).ToString('yyyyMMdd-HHmmss')
        echo "current_time=$current_time" >> $env:GITHUB_OUTPUT
        echo "current_short_time=$current_short_time" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Create or update Release
      id: create_or_update_release
      uses: GongT/actions-recreate-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: latest
          release_name: Latest
          body: |
            The latest build (${{ steps.get_time.outputs.current_time }}) in master branch.
          draft: false
          prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_or_update_release.outputs.upload_url }}
        asset_path: ./LogGenius-${{ github.ref_name }}.zip
        asset_name: LogGenius-${{ steps.get_time.outputs.current_short_time }}.zip
        asset_content_type: application/zip